name: Daily Bearable Sync

on:
  schedule:
    - cron: "5 6 * * *"  # runs daily at 6:05 AM UTC (8:05 AM in Poland)
  workflow_dispatch:      # allows manual trigger from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pandas pydrive2

      - name: Run update_data.py
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: python update_data.py
